version: '3.8'  

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - monitoring
    ports:
      - "9090:9090"  
    volumes:
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    networks: 
      - monitoring
    ports:
      - "3000:3000"
    volumes:
      - node_app_logs:/var/log/node-app
  
  loki:
    image: grafana/loki:2.7.1
    container_name: loki
    networks:
      - monitoring
    ports: 
      - 3100:3100
    volumes: 
      - ./loki-config.yml:/etc/loki/local-config.yaml 
      - loki_data:/loki 
    command: 
      - '-config.file=/etc/loki/local-config.yaml'

  promtail:
    image: grafana/promtail:2.7.1 
    container_name: promtail
    networks:
      - monitoring
    ports:
      - 9080:9080
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - node_app_logs:/var/log/node-app
    command:
      - '-config.file=/etc/promtail/config.yml'
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3001:3000
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-storage:
  loki_data:
  node_app_logs:


